default: &defaults
  automated_impact_email_feedback_survey:
    cron: "30 8 * * *"
    class: "EnquiryFeedbackSurveySender"

development:
  <<: *defaults
  cron:  "* * * * *"


staging:
  <<: *defaults

production:
  <<: *defaults