schedule_automated_impact_email_job:
  cron: "30 8 * * *"
  class: "SendImpactEmailToMatchingEnquiriesWorker"
  queue: default
  active_job: true

schedule_volume_import_opps_job:
  cron: "30 2 * * *"
  class: "RetrieveVolumeOpps"
  queue: default
  active_job: true